version: '3.8'

services:
  ventilos_postgres:
    image: postgres:18.0
    volumes:
      - postgres_data_ventilos:/var/lib/postgresql
    environment:
      POSTGRES_DB: ventilos
      POSTGRES_USER: ventilos
      POSTGRES_PASSWORD: ventilos
    ports:
      - 5433:5432

volumes:
  postgres_data_ventilos:
